### ISSUE TITLE
Remove un need variables

### ISSUE THREAD

**Issue by talkol** [orbs-network/nexus-harvestfinance#4]
In NexusSushiStrategy_WETH.sol

```
address public orbsInsurance;
uint256 public orbsRewardsSharingNumerator;
uint256 public orbsRewardsSharingDenominator;
```

**Comment by ordd** [comment]
https://github.com/orbs-network/nexus-harvestfinance/commit/19511a827c6f2e1a18fc9549fa091fa6e01adb9d

@talkol @DanielZlotin
