### ISSUE TITLE
Create a small script to take the most recent NexusLPSushi.sol

### ISSUE THREAD

**Issue by talkol** [orbs-network/nexus-harvestfinance#8]
Right now we need to manually update the NexusLPSushi version inside this repo and take it from the nexus-sushiswap

Let's create a simple script that performs this update, clones nexus-sushiswap and takes its most recent code

Also - run this script to update NexusLPSushi to the latest

**Comment by DanielZlotin** [comment]
wontfix - deploy to mainnet
